import { createMonitor, createMonitorBody, monitorBody } from "./api/monitor.doc";
import swaggerAutogen from "swagger-autogen";
swaggerAutogen({ openapi: "3.0.0"});
import "dotenv/config";

let host = process.env.HOST !== '0.0.0.0' ? process.env.HOST : "localhost";

const outputFile = "./docs/swagger_output.json";

const endpointsFiles = [
  "./router.ts",
  "./controllers/event.controller.ts",
  "./controllers/monitor.controller.ts",
  "./controllers/main.controller.ts",
];

const doc = {
  info: {
    version: "0.1.0",
    title: "Monitor Engine API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `${host}:${process.env.PORT}`,
  // basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  servers: [
    {
      url: "http://localhost:8000",
      description: "Local server",
    },
  ],

  tags: [
    {
      name: "Monitor",
      description: "Endpoints for monitoring websites",
    },
    {
      name: "Events",
      description: "Endpoints for viewing events",
    },
    {
      name: "Main",
      description: "Endpoints for general API functionality",
    },
  ],
  components: {
    securitySchemes: {
      Bearer: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
        in: "header",
      },
    },
    schemas: {
      // Monitor: { ...monitorBody },
      // CreateMonitorBody: { ...createMonitorBody },
    },
  },
  security: [
    {
      Bearer: [],
    },
  ],
  definitions: {
    Monitor: { ...monitorBody },
    // createMonitorBody,
    CreateMonitor: { ...createMonitor },
    CreateMonitorBody: {
      content: {
        "application/json": {
          type: "object",
          properties: {
            title: {
              example: "Example Monitor",
            },
            projectId: {
              example: "1234567",
            },
            url: {
              example: "https://ikehunter.com",
            },
            statusCode: {
              example: 200,
            },
            users: {
              example: [
                {
                  userId: "123456",
                  email: "user@example.com",
                },
              ],
            },
          },
        },
      },
    },
  },
};


export const initializeSwagger = async () => {
  await swaggerAutogen(outputFile, endpointsFiles, doc);
}
