image: docker:26.1.3
services:
  - docker:26.1.3-dind

stages:
  - Build and Test

Test Project:
  stage: Build and Test
  image: docker:26.1.3
  services:
    - docker:26.1.3-dind
  script:
    - apk add --update docker-compose
    - docker-compose build
    - docker-compose run --rm monitor sh -c "npm run test"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
