image: docker:26.1.3
services:
  - docker:26.1.3-dind

stages:
  - Build and Test

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - apk update && apk add bash
  - apk update && apk add gettext

Test Project:
  stage: Build and Test
  image: docker:26.1.3
  services:
    - docker:26.1.3-dind
  script:
    - apk add --update docker-compose
    # - echo -e "@development-suite:registry=https://gitlab.com/api/v4/projects/59180469/packages/npm/" > .npmrc
    # - echo -e "//${CI_SERVER_HOST}/api/v4/projects/59180469/packages/npm/:_authToken=$GITLAB_NPM_ACCESS_TOKEN" >> .npmrc

    - envsubst < ./.gitlab/templates/npmrc-template.txt > .npmrc
    # - echo -e "@development-suite:registry=https://gitlab.com/api/v4/projects/59180469/packages/npm/ \n//gitlab.com/api/v4/projects/59180469/packages/npm/:_authToken=\"$GITLAB_NPM_ACCESS_TOKEN\"" > .npmrc
    # - echo -e "@development-suite:registry=https://gitlab.com/api/v4/projects/59180469/packages/npm/" > .npmrc
    # - echo -e "//gitlab.com/api/v4/projects/59180469/packages/npm/:_authToken=\"${GITLAB_NPM_ACCESS_TOKEN}\"" >> .npmrc
    - docker-compose build
    - docker-compose run --rm monitor sh -c "npm run test"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|production|staging)$/ || $CI_COMMIT_BRANCH =~ /^(main|production|staging)$/'
