version: '3.9'

services:
  monitor:
    build:
      context: .
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./src:/src
      - ./logs:/logs
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - NODE_ENV=development
      - LOGGING_LEVEL=verbose
      - EMAIL_USER=tests@ikehunter.dev
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - CENTRAL_ENGINE_URL=http://localhost:8000
      - CENTRAL_NOTIFY_ENDPOINT=/engine/notify/
      - CENTRAL_GET_ENDPOINT=/engine/get/
      - MONGO_URI=mongodb://root:changeme@mongo-monitor
      
      - MONGO_PORT=27017
      - MONGO_DB=monitor
    depends_on:
      - mongo-monitor
    command: npm run dev
    networks:
      - cluster
  
  mongo-monitor:
    image: mongo:6.0.9
    container_name: mongo-monitor
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo-data-dsm:/data/db
    command: mongod --quiet --logpath /dev/null --bind_ip_all
    networks:
      - cluster
    
volumes:
  mongo-data-dsm:

networks:
  cluster:
    name: clientcrm_default
    external: true

      
    