version: '3.9'

services:
  monitor:
    build:
      context: .
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./src:/app/src
      - ./coverage:/app/coverage
      - ./logs:/app/logs
      - ./test-report:/app/test-report
      - ./generated-data:/app/generated-data
      - ./package.json:/app/package.json
      - ./.env:/app/.env
    environment:
      - HOST=0.0.0.0
      - PORT=9000
      - MONGO_URI=mongodb://root:changeme@mongo-monitor:27017
    depends_on:
      - mongo-monitor
    command: npm run dev

  
  mongo-monitor:
    image: mongo:6.0.9
    container_name: mongo-monitor
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo-monitor-data:/data/db
    command: mongod --quiet --logpath /dev/null --bind_ip_all
  
  coverage:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./coverage:/usr/share/nginx/html
    logging:
      driver: "none"
  
  report:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./test-report:/usr/share/nginx/html
    logging:
      driver: "none"
    
volumes:
  mongo-monitor-data:

    