version: '3.9'

services:
  monitor:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./src:/app/src
      - ./coverage:/app/coverage
      - ./logs:/app/logs
      - ./.git:/app/.git
      - ./test-report:/app/test-report
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8000
      - LOGGING_LEVEL=verbose
      - EMAIL_USER=tests@ikehunter.dev
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - CENTRAL_ENGINE_URL=http://localhost:8000
      - CENTRAL_NOTIFY_ENDPOINT=/engine/notify/
      - CENTRAL_GET_ENDPOINT=/engine/get/
      - MONGO_URI=mongodb://root:changeme@mongo-monitor:27017
      - AUTH_SERVICE_URL=http://localhost:8000/auth/
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - mongo-monitor
    command: npm run dev

  
  mongo-monitor:
    image: mongo:6.0.9
    container_name: mongo-monitor
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo-data-dsm:/data/db
    command: mongod --quiet --logpath /dev/null --bind_ip_all
  
  coverage:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./coverage:/usr/share/nginx/html
    logging:
      driver: "none"
  
  report:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - ./test-report:/usr/share/nginx/html
    logging:
      driver: "none"
    
volumes:
  mongo-data-dsm:

    