version: '3.9'

services:
  monitor:
    build:
      context: .
    ports:
      - "9001:9000"
    restart: always
    container_name: monitor-engine
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./package.json:/app/package.json
    env_file:
      - ./.env
    environment:
      - NODE_ENV=network
      - KAFKA_GROUP_ID=monitor-engine
      - LOG_NS=monitor
      - PORT=9000
      # MONGO_URI=mongodb://root:changeme@mongo-monitor:27017
      - MONGO_URI=mongo-monitor:27017
      - MONGO_USER=root
      - MONGO_PASS=changeme
    depends_on:
      - mongo-monitor
    command: npm run dev
    networks:
      - cluster
  
  mongo-monitor:
    image: mongo:6.0.9
    container_name: mongo-monitor
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo-data-dsm:/data/db
    command: mongod --quiet --logpath /dev/null --bind_ip_all
    networks:
      - cluster
      
  # monitor-socket:
  #   build:
  #     context: .
  #   ports:
  #     - "8333:8333"
  #   restart: always
  #   container_name: monitor-socket
  #   volumes:
  #     - ./src:/app/src
  #     - ./socket:/app/socket
  #     - ./package.json:/app/package.json
  #   env_file:
  #     - ./.env
  #   environment:
  #     - NODE_ENV=network
  #     - KAFKA_GROUP_ID=monitor-socket
  #     - LOG_NS=socket
  #     - PORT=8333
  #   depends_on:
  #     - mongo-monitor
  #   command: npm run socket
  #   networks:
  #     - cluster
    
volumes:
  mongo-data-dsm:

networks:
  cluster:
    name: cluster_network
    external: true

      
    