version: '3.9'

services:
  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/logs
    environment:
      - HOST=api
      - PORT=8000
      - LOGGING_LEVEL=verbose
      - EMAIL_USER=tests@ikehunter.dev
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - CENTRAL_ENGINE_URL=http://localhost:8000
      - CENTRAL_NOTIFY_ENDPOINT=/engine/notify/
      - CENTRAL_GET_ENDPOINT=/engine/get/
      - MONGO_URI=mongodb://root:changeme@mongo:27017
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6.0.9
    container_name: mongo-dsm
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo-data-dsm:/data/db
    command: mongod --quiet --logpath /dev/null
    
volumes:
  mongo-data-dsm:

      
    