// const swaggerAutogen = require('swagger-autogen')()
const swaggerAutogen = require("swagger-autogen")({ openapi: "3.0.0" });

const outputFile = "/src/swagger/swagger_output.json";

const endpointsFiles = [
  "../router",
  "../controllers/main.controller",
  "../controllers/monitor.controller",
];

const doc = {
  info: {
    version: "0.1.0",
    title: "Monitor Engine API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `${process.env.HOST}:${process.env.PORT}}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
  ],
  components: {
    securitySchemes: {
      Bearer: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
        in: "header",
      },
    },
  },
  security: [
    {
      Bearer: [],
    },
  ],
  
};

swaggerAutogen(outputFile, endpointsFiles, doc);
